version: '3.4'

services:
  clientwebapi:
    image: ${DOCKER_REGISTRY-}clientwebapi
    build:
      context: .
      dockerfile: ClientWebApi/Dockerfile
  
  serverwebapi:
    image: ${DOCKER_REGISTRY-}serverwebapi
    build:
      context: .
      dockerfile: ServerWebApi/Dockerfile

  datamigration:
    image: ${DOCKER_REGISTRY-}datamigration
    build:
      context: ./DataMigration
      dockerfile: Dockerfile

  referencedatabase:
    image: postgres:14
    container_name: postgres

  pgadmin:
    image: dpage/pgadmin4
    environment:
     - PGADMIN_DEFAULT_EMAIL=test@me.com
     - PGADMIN_DEFAULT_PASSWORD=letmein
    ports:
     - 5050:80

  Jaeger: 
    image: jaegertracing/all-in-one #https://www.jaegertracing.io/docs/1.21/getting-started/#all-in-one
    ports:
    - 5775:5775
    - 6831:6831
    - 6832:6832
    - 5778:5778
    - 16686:16686 #Jaeger UI
    - 14268:14268
    - 9411:9411