version: '3.4'

services:
  clientwebapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - OTEL_EXPORTER_JAEGER_AGENT_HOST=Jaeger
      - OTEL_EXPORTER_JAEGER_AGENT_PORT=6831
    ports:
      - "8000:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  serverwebapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=referencedatabase;Database=reference;User Id=postgres;Password=LetMeIn!
      - OTEL_EXPORTER_JAEGER_AGENT_HOST=Jaeger
      - OTEL_EXPORTER_JAEGER_AGENT_PORT=6831
    ports:
      - "8001:80"

  datamigration:
    environment:
      - ConnectionStrings__DefaultConnection=Server=referencedatabase;Database=reference;User Id=postgres;Password=LetMeIn!

  referencedatabase:
    environment:
      POSTGRES_PASSWORD: LetMeIn!
      POSTGRES_DB: reference
    ports:
    - "5432"