version: '3.4'

services:
  clientwebapi:
    image: ${DOCKER_REGISTRY-}clientwebapi
    build:
      context: .
      dockerfile: ClientWebApi/Dockerfile
  serverwebapi:
    image: ${DOCKER_REGISTRY-}serverwebapi
    build:
      context: .
      dockerfile: ServerWebApi/Dockerfile

